#! /bin/bash

apt-get install -yq ddclient

# Configure dyndns client
cat >/etc/ddclient.conf << EOF
# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf
protocol=dyndns2
use=web
server=members.dyndns.org
login=tecak
password=''
sclh.selfip.net
EOF

chmod 600 /etc/ddclient.conf

/usr/sbin/ddclient -daemon 300 -syslog

